version: '3.3'

networks:
  mal:
  
services:
  mal:
    image: map
    container_name: map
    restart: always
    networks:
      - mal    
    ports:
      - 5001:5000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_BACKEND=redis://redis:6379/0
      - MAX_WORKERS=5
      - REDIS_HOST=host.docker.internal
      - MONGO_DBNAME=mal
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=mongoadmin
      - MONGO_PASSWORD=mongoadmin
      - MONGO_AUTHDB=admin
      - NEO4J_URL=http://neo4j:7474
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=daxiahyh
    volumes:
      - /tmp/app:/tmp

  celery_s:
    image: celery_s
    container_name: celery_s
    restart: always
    networks:
      - mal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_BACKEND=redis://redis:6379/0
      - MAX_WORKERS=5
      - REDIS_HOST=host.docker.internal
      - MONGO_DBNAME=mal
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=mongoadmin
      - MONGO_PASSWORD=mongoadmin
      - MONGO_AUTHDB=admin
      - NEO4J_URL=http://neo4j:7474
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=daxiahyh
      - CUCKOO_URL=http://10.112.254.160:8000
      - CUCKOO_TOKEN="Bearer PYK9j3-G4zyScn4EDW3eKg"
    volumes:
      - /tmp/app:/tmp  

  kg:
    image: kg
    container_name: kg
    restart: always
    networks:
      - mal
    ports:
      - 3000:3000
    environment:
      NEO4J_HOST: neo4j
      NEO4J_PORT: 7688
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: daxiahyh

  redis:
    image: redis
    container_name: redis
    networks:
      - mal
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - mal
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      - mal
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin

  neo4j:
    image: neo4j
    container_name: neo4j
    networks:
      - mal
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data
  